"""Email sending functionality for summaries."""
import re
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from html import escape

from shared.config import settings


def _markdown_to_html(text: str) -> str:
    """Convert the LLM markdown output to clean HTML."""
    lines = text.split("\n")
    html_lines = []
    for line in lines:
        # Section headings: ## 🔴 Action Required
        if line.startswith("## "):
            heading = escape(line[3:].strip())
            html_lines.append(f'<h2 style="margin:24px 0 8px;font-size:16px;border-bottom:2px solid #eee;padding-bottom:6px">{heading}</h2>')
        # Horizontal rule
        elif line.strip() in ("---", "***", "___"):
            html_lines.append('<hr style="border:none;border-top:1px solid #ddd;margin:20px 0">')
        # Empty line → spacing
        elif line.strip() == "":
            html_lines.append('<div style="margin:4px 0"></div>')
        else:
            # Bold **text**
            formatted = re.sub(
                r'\*\*(.+?)\*\*',
                r'<strong>\1</strong>',
                escape(line)
            )
            # Bullet points
            if line.startswith("- ") or line.startswith("* "):
                formatted = formatted[2:]
                html_lines.append(
                    f'<div style="padding:6px 0 6px 12px;border-left:3px solid #e0e0e0;margin:4px 0;line-height:1.5">{formatted}</div>'
                )
            else:
                html_lines.append(f'<div style="line-height:1.5;padding:2px 0">{formatted}</div>')
    return "\n".join(html_lines)


def send_summary_email(summary_text: str, to_addr: str) -> None:
    """Send the email digest via SMTP.

    Args:
        summary_text: Markdown-formatted summary text
        to_addr: Recipient email address

    Raises:
        ValueError: If summary_text is empty or to_addr is invalid
    """
    if not summary_text or not summary_text.strip():
        raise ValueError("summary_text cannot be empty")
    if not to_addr or "@" not in to_addr:
        raise ValueError(f"Invalid recipient email: {to_addr}")

    today = date.today().strftime("%A %d %B %Y")
    subject = f"☀️ Daily Email Summary — {today}"

    body_html = _markdown_to_html(summary_text)
    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:Arial,sans-serif;font-size:14px;color:#333">
  <div style="max-width:600px;margin:24px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.1)">
    <div style="background:#1a73e8;padding:20px 24px">
      <div style="color:#fff;font-size:20px;font-weight:bold">☀️ Daily Email Summary</div>
      <div style="color:#cfe3ff;font-size:13px;margin-top:4px">{today}</div>
    </div>
    <div style="padding:20px 24px">
      {body_html}
    </div>
    <div style="background:#f9f9f9;padding:12px 24px;font-size:12px;color:#888;border-top:1px solid #eee">
      Generated by SummerMail
    </div>
  </div>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.gmail_user
    msg["To"] = to_addr
    msg.attach(MIMEText(summary_text, "plain"))
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(settings.gmail_user, settings.gmail_app_password.get_secret_value())
        server.sendmail(settings.gmail_user, [to_addr], msg.as_string())
